baseURL = "https://davidferreira21.github.io/blog/"
title = "David Ferreira — Cloud & Platform Engineering"
theme = "PaperMod"
languageCode = "pt-br"

[params]
  ShowReadingTime = true
  ShowCodeCopyButtons = true

[menu]

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    identifier = "labs"
    name = "Labs"
    url = "/labs/"
    weight = 20

  [[menu.main]]
    identifier = "arquitetura"
    name = "Arquitetura"
    url = "/arquitetura/"
    weight = 30

  [[menu.main]]
    identifier = "devops"
    name = "DevOps"
    url = "/devops/"
    weight = 40


[params.profileMode]
  enabled = true
  title = "David Ferreira"
  subtitle = "Cloud • Platform Engineering • DevOps • GitOps"
  imageUrl = "/images/hero.png"
  imageTitle = "Cloud & Platform Engineering"
  imageWidth = 320
  imageHeight = 180


  [[params.profileMode.buttons]]
    name = "Labs"
    url = "/labs/"

  [[params.profileMode.buttons]]
    name = "Arquitetura"
    url = "/arquitetura/"